### ISSUE TITLE
Allow specifying an alternative provider for dns records

### ISSUE THREAD

**Issue by njoerd114** [terraform-aws-modules/terraform-aws-acm#111]
## Is your request related to a new offering from AWS?
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
We're managing our DNS Zones in a separate AWS Account. We'd like to use this module to provision ACM Certificates for products in their accounts.

## Describe the solution you'd like.
Add the option to specify an additional provider (defaults to the default provider).

## Describe alternatives you've considered.
One could also specify the validation records separately and not use this functionality from the module, however that would result in some overhead.

## Additional context
[Module Provider Docs](https://www.terraform.io/language/meta-arguments/module-providers)

**Comment by njoerd114** [comment]
#108 actually seams to achieve this...

**Comment by dannyibishev** [comment]
> #108 actually seams to achieve this...

I've been the forked repo I created for the above in a number of project and it works without issue. Sadly it's been two months and I've still not heard anything from the module Code owners. :'(

**Comment by MrKoopaKiller** [comment]
+1

**Comment by dhoppe** [comment]
@njoerd114 I understand your use case, but I do not think it is the responsibility of a Terraform module to support different AWS accounts. 

For example, the subdomain in account A could point to the nameservers of account B's hosted zone. 

Another possibility would be to use Terragrunt or Terramate.

**Comment by dannyibishev** [comment]
#114 Closes this issue. Thanks Anton 🥇
