### ISSUE TITLE
where do i get the value for zone_id? Error: NoSuchHostedZone: No hosted zone found with ID: Z2ES8B9AZ6SHAE

### ISSUE THREAD

**Issue by MispaMary** [terraform-aws-modules/terraform-aws-acm#119]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

**Comment by antonbabenko** [comment]
You can use [aws_route53_zone data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/route53_zone), for example. See [example code](https://github.com/terraform-aws-modules/terraform-aws-acm/blob/master/examples/complete-dns-validation/main.tf#L10).
