### ISSUE TITLE
Unable to set renewal_eligibility

### ISSUE THREAD

**Issue by SimonEdwardsMQA** [terraform-aws-modules/terraform-aws-acm#120]
## Is your request related to a problem? Please describe.
Since creating the certificate with this module, the renewal_eligibility has been changed to "ELIGIBLE". However, the module wants to revert this back to "INELIGIBLE" and I can't see a way of setting this or where the module is setting this argument.

## Describe the solution you'd like.
Allow **renewal_eligibility = "ELIGIBLE"** to be accepted by the module.

## Describe alternatives you've considered.
I'm unable to use ignore_changes

## Additional context
```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:

  # module.acm.aws_acm_certificate.this[0] has changed
  ~ resource "aws_acm_certificate" "this" {
        id                        = "arn:aws:acm:eu-west-2:8124********:certificate/cc7f****-80**-49**-8f**-2489********"
      ~ renewal_eligibility       = "INELIGIBLE" -> "ELIGIBLE"

```

**Comment by dhoppe** [comment]
@SimonEdwardsMQA Please check if the mentioned criteria are met. https://github.com/hashicorp/terraform-provider-aws/issues/8925#issuecomment-500480461

**Comment by SimonEdwardsMQA** [comment]
> @SimonEdwardsMQA Please check if the mentioned criteria are met. [hashicorp/terraform-provider-aws#8925 (comment)](https://github.com/hashicorp/terraform-provider-aws/issues/8925#issuecomment-500480461)

The issue isn't with the cert itself, that is eligible, the problem I'm having is setting the renewal_eligibility so that Terraform is aware that it;s eligible.

**Comment by dhoppe** [comment]
As far as I understood `renewal_eligibility` can not be managed directly by the AWS provider and is just provided as output. 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate#renewal_eligibility

**Comment by SimonEdwardsMQA** [comment]
How do I get around the "Objects have changed outside of Terraform" issue when I run a plan? There must be something in TF that is trying to set renewal_eligibility

**Comment by antonbabenko** [comment]
I agree with @dhoppe and there is nothing we can do in this module. It is Terraform AWS provider issue.
