### ISSUE TITLE
Ability to support multiple hostnames and DNS zones

### ISSUE THREAD

**Issue by rapides** [terraform-aws-modules/terraform-aws-acm#136]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

I cannot select more `zone_id` when I want to support more than one DNS name with totally different hostnames. In order to create CloudFront distribution that uses 2 totally different domains at the same time (example: `example.com` and `example.co`) and I need to use a single SSL certificate that whitelists 2 different hostnames. In such cases, each domain has to have a separate DNS zone.

## Describe the solution you'd like.

Ability to enter domains and zones together via a single variable, so you can easily distinguish when you need to create DNS records in separate DNS zones.

## Describe alternatives you've considered.

N/A

**Comment by amontalban** [comment]
We are having the same need, would be great to genera an ACM certificate with multiple domains so we don't have to create multiple CloudFront distributions.

**Comment by amontalban** [comment]
@rapides can you try #137 and see if that works for you? Thanks!

**Comment by phuhl** [comment]
I have the same issue

**Comment by phuhl** [comment]
Issue still perists

**Comment by phuhl** [comment]
Issue still perists

**Comment by antonbabenko** [comment]
https://github.com/terraform-aws-modules/terraform-aws-acm/pull/137#pullrequestreview-1662067778 - my review is still relevant and someone can take it further and work on improvements.

**Comment by alemarmed** [comment]
Hi @amontalban, do you intend to resume #137? Otherwise I think I could make requested changes.

**Comment by phuhl** [comment]
Issue still perists, I don't know the code in here at all, so I am not sure, it makes sense for me to work on this, but @amontalban maybe you could create a new PR based on #137?

**Comment by phuhl** [comment]
Issue still persists, waiting for https://github.com/terraform-aws-modules/terraform-aws-acm/pull/149

**Comment by phuhl** [comment]
Issue still persists, waiting for https://github.com/terraform-aws-modules/terraform-aws-acm/pull/149

**Comment by phuhl** [comment]
Issue still persists, waiting for https://github.com/terraform-aws-modules/terraform-aws-acm/pull/149

**Comment by phuhl** [comment]
Issue still persists, waiting for https://github.com/terraform-aws-modules/terraform-aws-acm/pull/149

**Comment by phuhl** [comment]
Issue still persists, waiting for https://github.com/terraform-aws-modules/terraform-aws-acm/pull/149

**Comment by antonbabenko** [comment]
@phuhl  it's your turn to check it out and open an issue if you see something wrong. I'm sorry it took so long to get this one reviewed and merged.

**Comment by phuhl** [comment]
Thank you for putting the work in :)
