### ISSUE TITLE
Cycle error

### ISSUE THREAD

**Issue by lukasmrtvy** [terraform-aws-modules/terraform-aws-acm#138]
Can We introduce the multi-provider support https://github.com/terraform-aws-modules/terraform-aws-acm/issues/25 ( one for the certificate and the other for vadilation )? Or at least fix the cycle error when using `for_each` to create multiple certificates ? https://github.com/terraform-aws-modules/terraform-aws-acm/issues/121 and https://github.com/terraform-aws-modules/terraform-aws-acm/issues/131

```
locals {
  certificates = [{
    name = foo.bar.com
    sans = ["foo.bar.com"]
  },
  {
    name = john.doe.com
    sans = ["john.doe.com"]
  }]
}

module "acm" {
  for_each = { for c in local.certificates : c.name => c }
  source  = "terraform-aws-modules/acm/aws"
  domain_name  = each.value.name
  subject_alternative_names = each.value.sans
  create_route53_records  = false
  validation_record_fqdns = module.route53_records[each.value.name].validation_route53_record_fqdns
}

module "route53_records" {
  for_each  = { for c in local.certificates : c.name => c }
  source  = "terraform-aws-modules/acm/aws"
  providers = {
    aws = aws.other_account
  }
  create_certificate          = false
  create_route53_records_only = true
  distinct_domain_names = module.acm[each.value.name].distinct_domain_names
  zone_id               = "other_account_zone_id"
  acm_certificate_domain_validation_options = module.acm[each.value.name].acm_certificate_domain_validation_options
}
```

Thanks

**Comment by antonbabenko** [comment]
Please take a look at this example - https://github.com/terraform-aws-modules/terraform-aws-acm/blob/master/examples/complete-dns-validation/main.tf#L54-L101

This is already implemented in this module.

**Comment by lukasmrtvy** [comment]
@antonbabenko are You sure? https://github.com/terraform-aws-modules/terraform-aws-acm/blob/master/variables.tf#L43 is a string, not a map, not an array, this implies that only a single certificate can be created. All these issues refer to the option to create multiple certificates.

**Comment by antonbabenko** [comment]
That's correct - `domain_name` is a string, but `subject_alternative_names` is a list. You need to provide such inputs. Please take a look at the example provided.
