### ISSUE TITLE
CloudFront Use Cases

### ISSUE THREAD

**Issue by mrcrilly** [terraform-aws-modules/terraform-aws-acm#14]
Greetings!

I was considering using this module until I ran into a problem: I need to be able to create a certificate in `ap-southeast-2` AND `us-east-1` using the same TLD and SAN records. That is to say:

```
module "my-domain-name" {
  source = "../../modules/terraform-aws-acm"

  domain_name = "my-domain-name.com"
  zone_id     = data.aws_route53_zone.my-domain-name.zone_id

  subject_alternative_names = [
    "www.my-domain-name.com",
    "example.my-domain-name.com",
  ]

  validation_allow_overwrite_records = true
}

module "my-domain-name_cfn" {
  # CloudFront requires the certificate to be in the US
  providers = {
    "aws" = aws.us
  }

  source = "../../modules/terraform-aws-acm"

  domain_name = "my-domain-name.com"
  zone_id     = data.aws_route53_zone.my-domain-name.zone_id

  subject_alternative_names = [
    "www.my-domain-name.com",
    "example.my-domain-name.com",
  ]

  validation_allow_overwrite_records = true
}
```

I need an ACM managed TLS certificate in Australia for our ALB. I also need the same certificate (same in the domain/SAN sense) in the US (`us-east-1`) because that's a CloudFront requirement. This should be a simple case of just using your module twice.

I'm worried that this will introduce race conditions, however. Also, if I create these resources and re-run, it's not idempotent for somewhat obvious reasons (the CNAME record name and value are calculated from the fixed inputs you give ACM, so they collide in the DNS Zone.)

Besides going back to my more verbose (but woking) code, can you make any suggestions or think of a way the module could be updated to accomodate this?

**Comment by antonbabenko** [comment]
Sounds like a proper use-case. Route53 records are global across all regions, so I would recommend creating one ACM certificate with `validate_certificate = true` and another with `validate_certificate = false` to have DNS management idempotent.

Setting `validation_allow_overwrite_records = true` is not so important if DNS will be managed for just one certificate.

**Comment by mrcrilly** [comment]
I actually managed to resolve this and it was obvious.

I essentially created two certificates but only one set of CNAME records in the DNS Zone (Route53). The reason for this is because the certificates are identical, so the CNAME records are identical too. Therefore, you...

1. Create the first certificate
1. Create the second certificate (in the US)
1. Get the DNS records required to validate it
1. Update the DNS Zone in Route53
1. Create two DNS validation resources to wait for the certificate to be issued
1. Done.

Because both certificates result in identical CNAME records, the validation checks both pass just fine.

Using `validate_certificate = false` might speed things up a bit, so I might try that, but leaving it as `true` did not introduce any errors, race conditions or problems for me.

Thank you for your time, @antonbabenko.
