### ISSUE TITLE
aws_acm_certificate.this is empty tuple

### ISSUE THREAD

**Issue by robsonscm** [terraform-aws-modules/terraform-aws-acm#26]
Hi, there is a problem when we use the  create_certificate=false.
The variable in the locals called **validation_domains** is not taking in account the flag.
As it does not create the certificate,  the FOR operation fails with the message:
Error: Invalid index

```
on .terraform/modules/resources_accounts.cloudops_prod_acm/terraform-aws-modules-terraform-aws-acm-984f018/main.tf line 6, in locals:
   6:   validation_domains = [for k, v in aws_acm_certificate.this[0].domain_validation_options : tomap(v) if contains(local.distinct_domain_names, v.domain_name)]
    |----------------
    | aws_acm_certificate.this is empty tuple

The given key does not identify an element in this collection value.
```

I believe the solution would be like this:
```
validation_domains = var.create_certificate ? [for k, v in aws_acm_certificate.this[0].domain_validation_options : tomap(v) if contains(local.distinct_domain_names, v.domain_name)] : []
```

Let me know if you need any other info.
Tks
Robson

**Comment by atheiman** [comment]
We just hit this problem too in terraform 0.12.12

**Comment by robsonscm** [comment]
You’re right. I forgot to mention the version. Terraform 12.12 for me too.
Actually I cloned the module and did the change I suggested locally. It works fine that way.
Cheers

**Comment by richardcase** [comment]
I'm encountering this issue when using https://github.com/terraform-aws-modules/terraform-aws-atlantis. So it would be great to get #28 approved and merged.

**Comment by antonbabenko** [comment]
[v2.4.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.4.0) of this module has been just released where this bug is fixed.

**Comment by xueshanf** [comment]
@antonbabenko I have spent hours trying to figure out why I am still hitting the issue: 
```Error: Invalid index

  on /Users/sfeng/projects/cirrus/kubernetes-services/sub-projects/eks-cluster/common/terraform-modules/terraform-aws-acm/main.tf line 6, in locals:
   6:   validation_domains = var.create_certificate ? [for k, v in aws_acm_certificate.this[0].domain_validation_options : tomap(v) if contains(local.distinct_domain_names, replace(v.domain_name, "*.", ""))] : []
    |----------------
    | aws_acm_certificate.this is empty tuple

The given key does not identify an element in this collection value.
aws_acm_certificate.this is empty tuple
```
I am on Terraform 0.12.23, ACM module v2.5.0, which  is supposed to fix this.  The same code runs on another AWS route53 domain just fine. Any idea where should  I  look? Thanks!
