### ISSUE TITLE
Adding wildcard domain as a subject alternative name breaks the module 

### ISSUE THREAD

**Issue by reegnz** [terraform-aws-modules/terraform-aws-acm#3]
For example try to run the module with a similar config to the one in the README. If you add the wildcard domain as a SAN, terraform will fail because ACM provides the same challenge name and value for both domains.

**Comment by reegnz** [comment]
The error is as described in #2.

**Comment by reegnz** [comment]
In general the issue 8s not with SAN and not with wildcard domains in general. The issue is when the same domain is listed both with and without the wildcard, ACM provides the exact same challenge CNAME record.

**Comment by mariodavid** [comment]
I'm facing the very same problem. When using the example from the README.md:

```module "acm" {
  domain_name  = "my-domain.com"

  subject_alternative_names = [
    "*.my-domain.com",
  ]
}
```

Then it will create two exact same DNS entries. This is true as AWS describes it in their FAQ:
```
Notice that ACM removes the wildcard label (*) when generating CNAME records for wildcard names. As a result, the CNAME record generated by ACM for a wildcard name (such as *.example.com) is the same record returned for the domain name without the wildcard label (example.com).
```

see: https://aws.amazon.com/certificate-manager/faqs/?nc1=h_ls

Do you have any idea on how to handle this case?

**Comment by DMonCode** [comment]
You could split var.subject_alternative_names into two lists, one wildcard and one domain. Merge both lists for the actual SAN but only use the domain list for the route53 validation.

Other option is to use template file to strip the "*." from the domain.

```
variable "subject_alternative_name" {
  default = [
    "example.com",
    "*.example.com",
    "example.org",
    "*.example.org"
  ]
}

data "template_file" "breakup_san" {
  count = "${length(var.subject_alternative_name)}"
  template = "${replace(element( var.subject_alternative_name , count.index), "*.", "")}"
}

output "merge" {
  value = "${distinct(data.template_file.breakup_san.*.rendered)}"
}
```

```
# result
$  terraform apply
data.template_file.breakup_san[2]: Refreshing state...
data.template_file.breakup_san[0]: Refreshing state...
data.template_file.breakup_san[3]: Refreshing state...
data.template_file.breakup_san[1]: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

merge = [
    example.com,
    example.org
]
```

**Comment by MattDevUK** [comment]
Is this related to the fact that the Terraform run will fail due to duplicate DNS records being created for the verification?
Didn't see it mentioned specifically, but the config referenced here, I am seeing a fail due it trying to make the same verification record twice. 

When looking into it, in the AWS provider v2.0.0 (Released Feb 27th) they changed the "allow overwrite" default value from True to False, and as this module doesn't accept that value to be passed in, it just takes the default. Meaning this causes an issue when it tries to make duplicate verification records when using any provider version >=2.0.0

Commit in the provider: https://github.com/terraform-providers/terraform-provider-aws/commit/a8c6bdfe1244f9a572b7bf15398d7137f360c83c#diff-7f12b54e3263d749179bfb63338a8919

> I'm facing the very same problem. When using the example from the README.md:
> 
> ```
> module "acm" {
>   domain_name  = "my-domain.com"
> 
>   subject_alternative_names = [
>     "*.my-domain.com",
>   ]
> }
> ```
> 
> Then it will create two exact same DNS entries. This is true as AWS describes it in their FAQ:
> 
> ```
> Notice that ACM removes the wildcard label (*) when generating CNAME records for wildcard names. 
> As a result, the CNAME record generated by ACM for a wildcard name (such as *.example.com) is the same record returned for the domain name without the wildcard label (example.com).
> ```
> 
> see: https://aws.amazon.com/certificate-manager/faqs/?nc1=h_ls
> 
> Do you have any idea on how to handle this case?

**Comment by antonbabenko** [comment]
If you can use Terraform 0.12 then you can use [v2.0.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.0.0) which has been just released.

Make sure to pin module version to `~> v2.0` if you are using Terraform 0.12, and use `~> v1.0` if you are using Terraform 0.11.

I am going to look into #8 by @Tensho, which may be a feasible option. I don't want to spend a lot of time to support this module for Terraform 0.11.

**Comment by antonbabenko** [comment]
#8 is not quite there with wildcard support yet and I don't know how to make this module to automatically validate certificates with wildcards with Terraform 0.11 (and don't really want to spend time on that).

If anyone wants to spend time and make it complete for Terraform 0.11, please submit pull-request (and working example which confirms it).

I recommend upgrading to Terraform 0.12 and use [v2.0.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.0.0) of this module, if possible.
