### ISSUE TITLE
Certificate not ready for use immediately after acm_certificate resource creation

### ISSUE THREAD

**Issue by richardgavel** [terraform-aws-modules/terraform-aws-acm#37]
I have a TF using this module and the this_acm_certificate_arn output. However, since the output is only dependent upon the acm_certificate resource, it's available too soon, resulting in errors like this:

Error: Error creating API Gateway Domain Name: BadRequestException: The provided certificate does not exist.

One option is to use the aws_acm_certificate_validation.this.certificate_arn instead. Then the output won't be available until the cert is validated. You might have to adjust for the optional nature of the the validation resource.

**Comment by ibratoev** [comment]
Yeah, I hit the same issue. @richardgavel Have you tested your proposed solution?

**Comment by douglasnaphas** [comment]
I have another option in place on my fork of this project ([here](https://github.com/douglasnaphas/terraform-aws-acm/commit/a5c7b8e6d9fc666e8bcb490c32143f7dc8b560f3)). My work-in-progress solution is to output the cert object itself. That way, in my other module, which depends on the cert from this module, I take the cert as an input variable, and Terraform's implicit dependency resolution makes sure that the cert is ready before the depending module is created.

I need to deal with the fact that the list of certs called `aws_acm_certificate.this` may be empty, and maybe with the "optional nature of the validation resource" as mentioned by @richardgavel.

**Comment by antonbabenko** [comment]
This issue has been fixed and [v2.11.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.11.0) has been just released.

I wonder how did this issue manage to slip through so that I didn't see it in this repo before :)
