### ISSUE TITLE
Work with Terraform 0.12 ?

### ISSUE THREAD

**Issue by Jirka123456** [terraform-aws-modules/terraform-aws-acm#4]
facing this error after upgrade to terraform 0.12

Error: Missing resource instance key

  on modules/aws-acm/main.tf line 29, in resource "aws_route53_record" "validation":
  29:   name    = "${lookup(aws_acm_certificate.this.domain_validation_options[count.index], "resource_record_name")}"

Because aws_acm_certificate.this has "count" set, its attributes must be
accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    aws_acm_certificate.this[count.index]

Error: Missing resource instance key

  on modules/aws-acm/main.tf line 30, in resource "aws_route53_record" "validation":
  30:   type    = "${lookup(aws_acm_certificate.this.domain_validation_options[count.index], "resource_record_type")}"

Because aws_acm_certificate.this has "count" set, its attributes must be
accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    aws_acm_certificate.this[count.index]

Error: Missing resource instance key

  on modules/aws-acm/main.tf line 34, in resource "aws_route53_record" "validation":
  34:     "${lookup(aws_acm_certificate.this.domain_validation_options[count.index], "resource_record_value")}"

Because aws_acm_certificate.this has "count" set, its attributes must be
accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    aws_acm_certificate.this[count.index]

**Comment by mminks** [comment]
Having the same problem here. Can anyone help pls?

**Comment by antonbabenko** [comment]
[v2.0.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.0.0) has been just released after #9 has been merged (it includes other improvements, too).

Make sure to pin module version to `~> v2.0` if you are using Terraform 0.12, and use `~> v1.0` if you are using Terraform 0.11.

Please give it a try and let me know if there is anything wrong. :)
