### ISSUE TITLE
Support for aws provider v3

### ISSUE THREAD

**Issue by m1keil** [terraform-aws-modules/terraform-aws-acm#58]
Just wondering if support for the v3 provider is on the roadmap?

Cheers!

**Comment by antonbabenko** [comment]
Today.

**Comment by antonbabenko** [comment]
[v2.10.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.10.0) has been just released with AWS provider version 3 support.

**Comment by m1keil** [comment]
Thank you!
