### ISSUE TITLE
Issue to create validation record on Route53

### ISSUE THREAD

**Issue by fernandowiek** [terraform-aws-modules/terraform-aws-acm#63]
Hello,
I testing this module on my environment and a had an issue to create a validation record on my Route53 zone. I received this error message:

```
Error: InvalidInput: 1 validation error detected: Value 
'{"XXXXXXXX":{"comment":"Managed by Terraform","delegation_set_id":"XXXXXXXXXXXX","force_destroy":false, "id":"XXXXXXXXXX","name":"XXXXXXXX",
"name_servers":["ns-XXXXXXXX","ns-XXXXXXX","ns-XXXXXXXX","ns-XXXXXXXX"],"tags":{"Name":"XXXXXXX"},"vpc":[],"zone_id":"XXXXXXXXXXX"}}' 
at 'resourceId' failed to satisfy constraint: Member must have length less than or equal to 32
	status code: 400, request id: 944ad220-a145-4ce2-a69d-6de3655df0cf
```
I checked the dns validation entry created on ACM cert and it have more than 32 chars (33 to be exactly, ex: _11920dce777fe6243ea4e432353443a8).
If I force the record creation manually by AWS Console, it is created, but using terraform I got the error message above.

Do you know how to move forward and keep using this module?

Thank you

**Comment by fernandowiek** [comment]
I found an open issue for aws provider about this error: 
https://github.com/terraform-providers/terraform-provider-aws/issues/12238

**Comment by fernandowiek** [comment]
Hi,
I found the problem: I'm using a Route 53 module that outputs a map, not only the zone_id. I used the lookup function to get only the zone_id data on ACM module configuration and the validation worked perfectly.
See you!

**Comment by diegoaguilar** [comment]
@fernandowiek can you share more details on how you achieved or implemented this?
