### ISSUE TITLE
Compatibility with terraform 0.13

### ISSUE THREAD

**Issue by tomasbackman** [terraform-aws-modules/terraform-aws-acm#65]
It is upgraded for 0.12 but now compatibility for 0.13 would be good to have as well.. not sure if it requires some changes though..?

**Comment by antonbabenko** [comment]
Terraform 0.13 was supported already, but now I updated it to support Terraform 0.14 which is going live this month.

[v2.12.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.12.0) has been just released.
