### ISSUE TITLE
Release v2.13.0 destroys ACM validation records

### ISSUE THREAD

**Issue by nickelozz** [terraform-aws-modules/terraform-aws-acm#72]
I'm creating this issue to raise awareness.

With the release of [v2.13.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.13.0), performing a `terraform apply` will remove a duplicate route53 validation record (see more [here](https://github.com/terraform-aws-modules/terraform-aws-acm/pull/47)).

However, as mentioned in [this comment](https://github.com/terraform-aws-modules/terraform-aws-acm/pull/47#issuecomment-754778599), removing the duplicate record from the state file will effectively remove the actual record from AWS even though there's still 1 entry in the state file.

The way I solved this situation was by [removing](https://www.terraform.io/docs/cli/commands/state/rm.html) the duplicate record from the module with something like the following __before__ yielding the first `terraform apply` post-module upgrade:
```bash
terraform state rm module.acm.aws_route53_record.validation[1]
```
@antonbabenko perhaps a release note mentioning this situation could come in handy for people upgrading to this module version?

**Comment by antonbabenko** [comment]
Good point, `terraform state rm aws_route53_record.validation[1]` where `[1]` can be something else depending on your inputs. Could you open a PR that updated README about this?

**Comment by nickelozz** [comment]
Hi, @antonbabenko I can definitely do that. Do you have any preference on where to add this info? I'm thinking of putting it under `Notes`.

**Comment by antonbabenko** [comment]
Yes, `Notes` sounds reasonable.
