### ISSUE TITLE
Correct Terraform state addresses in README.md note about the off by one error

### ISSUE THREAD

**Issue by jmcgeheeiv** [terraform-aws-modules/terraform-aws-acm#80]
## Description

While useful, the note about removing the duplicate DNS entry is not quite correct. In particular, the state addresses are incorrect. Currently it says this:

* If you're upgrading to [v2.13.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.13.0) or above, you might be subject to [off-by-one validation record issue](https://github.com/terraform-aws-modules/terraform-aws-acm/pull/47#issuecomment-754778599). You can solve this without compromising existing validation records by issuing `terraform state rm <your_module_name>.validation[1]` where `[1]` can be a different index # depending on the number of validation records your module creates (you can check this with `terraform state list module.<your_module_name>.validation`).

I believe that the following would be clearer and more correct:

* If you're upgrading to [v2.13.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v2.13.0) or above, you might encounter the [off-by-one validation record issue](https://github.com/terraform-aws-modules/terraform-aws-acm/pull/47#issuecomment-754778599). You can check for and solve this without compromising existing validation with the following procedure:

  1. List the Route 53 validation DNS records:
        ```shell
      terraform state list module.<your_module_name>.aws_route53_record.validation
      ```
  2. If more than one validation record is present, delete all but `validation[0]` from the Terraform state:
      ```shell
      terraform state rm module.<your_module_name>.aws_route53_record.validation[1]
      # Also delete validation[2] and so on if present
      ```
(End of improved documentation)

## Versions

 - Terraform: 0.12..29

 - Provider(s):
   .
  ├── provider.aws
  ├── provider.local
  ├── module.acm
  │   └── provider.aws >= 2.53
  ├── module.gitlab-label
  ├── module.label
  ├── module.lambda-label
  └── module.this

 - Module:
  Terraform v0.12.29
  + provider.aws v3.34.0
  + provider.local v2.1.0

## Reproduction

- I am not using workspaces. I am using Terragrunt.

 - I cleared the local cache

- I followed the instructions in the note, but I have some corrections

**Comment by antonbabenko** [comment]
Thanks for the corrections.

I think the issue with the offset has been fixed in #89 and [v3.1.0](https://github.com/terraform-aws-modules/terraform-aws-acm/releases/v3.1.0) has been just released.

It should be rather safe to upgrade, too.
