### ISSUE TITLE
ACM DNS route 53 record is destroyed even if not created by current plan

### ISSUE THREAD

**Issue by rjcoelho** [terraform-aws-modules/terraform-aws-acm#84]
Say I have an route53 records already created to validate ACM certificates.

If i pass validation_allow_overwrite_records = true, It will "import" the existing record into the new state. Now if i destroy the plan it will delete the record.
If i pass validation_allow_overwrite_records = false it will fail because i have a record already created.

What I want is have bool variable to create a new record or use an existing one.
Any other suggestion ?
Thanks

**Comment by ZeePal** [comment]
if terraform has the resource in its statefile ("imported" with `overwrite=true`) then it will delete the resource with a destroy.
nothing can be done within this module to change the core nature of terraform sorry.

you maybe able to log an issue with the aws provider requesting a "do not delete" field so when the aws provider gets given the destroy request by terraform it will "ignore" the request and say it was destroyed successfully but leave the resource hanging.
if the aws provider is updated to support this for route53 records this module could then add a pass through option just like validation_allow_overwrite_records.

**Comment by naseemkullah** [comment]
> you maybe able to log an issue with the aws provider requesting a "do not delete" field so when the aws provider gets given the destroy request by terraform it will "ignore" the request and say it was destroyed successfully but leave the resource hanging.

@ZeePal  Do you know of any resources (aws provider or other) that have such a field?

**Comment by ZeePal** [comment]
> @ZeePal Do you know of any resources (aws provider or other) that have such a field?
@naseemkullah i cant recall which 1 but i think there is a resource in the aws provider, i had a quick look and couldnt find sorry. its definitely not a recommended approach (same as the overwrite option for route53) but there maybe use cases.

implementation should be easy as terraform core only asks the provider to destroy XYZ and it can just respond with "done" even tho it didnt do the real api call.

**Comment by naseemkullah** [comment]
Thanks for the info @ZeePal, fwiw my use case is cert with same domain names provisioned in multiple regions and having the flexibility to tear down and spin up regions at will. I guess I'll try to have only one region responsible for validation.
