### ISSUE TITLE
ACM replacement with wildcard subject_alternative_names

### ISSUE THREAD

**Issue by bcruik** [terraform-aws-modules/terraform-aws-acm#86]
Using the following module results in ACM replacement when when AWS responds with the subject_alternative_names in different orders.

```module "acm" {
  source  = "terraform-aws-modules/acm/aws"
  version = "~> v2.0"

  domain_name  = "example.net"
  zone_id      = data.aws_route53_zone.example.zone_id

  subject_alternative_names = [
    "*.example.net",
    "example.net",
  ]

  tags = {
    Name = "example.net"
  }
}
```

I've used this lifecycle to prevent changes when subject_alternative_names is out when not using a module. 
```
  lifecycle {
    prevent_destroy = true
    ignore_changes  = [subject_alternative_names]
  }
```

Just wondering if there's a better way to prevent a replacement certificate and hitting the aws cert domain limit (you can only generate 20 certs per a domain per an account)?

**Comment by antonbabenko** [comment]
`example.net` should not be repeated in `subject_alternative_names` since it is already mentioned in `domain_name`.

**Comment by bcruik** [comment]
> `example.net` should not be repeated in `subject_alternative_names` since it is already mentioned in `domain_name`.

@antonbabenko Oh I didn't know that! Thanks heaps for letting me know.

**Comment by bcruik** [comment]
``` source  = "terraform-aws-modules/acm/aws"
  version = "~> v2.0"

  domain_name  = "example.net"
  zone_id      = data.aws_route53_zone.example.zone_id

  subject_alternative_names = [
    "*.example.net"
  ]

  tags = {
    Name = "example.net"
  }
}
```

Results in `* missing *.example.net DNS validation record: _7ae43402b071a70114fcb8c41afa4554.example.net` - this doesn't seem right? Am I doing something wrong?

**Comment by bcruik** [comment]
Ignore above `data.aws_route53_zone.example.zone_id` wasn't example.net!

**Comment by antonbabenko** [comment]
The error indicates that there was no DNS record created in the `example.net` domain because you don't own it. If you use a real zone as I use in the examples code then it will work.
