### ISSUE TITLE
TF Registry documentation out of date

### ISSUE THREAD

**Issue by timcosta** [terraform-aws-modules/terraform-aws-acm#88]
## Description

https://registry.terraform.io/modules/terraform-aws-modules/acm/aws/latest seems to still have the documentation from the 2.0 major version, as the example shown there has `version = "~> 2.0"`. It's particularly weird because the outputs are updated (dont have the `this_` prefix) but the main section still says 2.0 which means anyone who copy/pastas the example there and looks at the outputs will get errors.

**Comment by antonbabenko** [comment]
Hi! I am not sure why it was like that but I pushed newer releases today and it seems to refresh that page.
