### ISSUE TITLE
Reapply the terraform without any changes in the argument - it recreates the resource again

### ISSUE THREAD

**Issue by bangau1** [terraform-aws-modules/terraform-aws-acm#90]
## Description

After `terraform apply` succesfully, then try to reapply again, it wants to destroy and apply again. Is it expected?

## Versions
 - Terraform: 1.0.1
 - Provider(s):
    - provider registry.terraform.io/hashicorp/aws v3.47.0
    - provider registry.terraform.io/hashicorp/helm v2.2.0
    - provider registry.terraform.io/hashicorp/kubernetes v2.3.2
    - provider registry.terraform.io/hashicorp/null v3.1.0
    - provider registry.terraform.io/hashicorp/random v3.1.0
 - Module: terraform-aws-modules/acm/aws 3.2.0

## Reproduction
- Using this code snippet below, tf apply and success.
- The reapply again by `terraform apply`, it mentions `Plan: 3 to add, 0 to change, 3 to destroy.`

### Code Snippet to Reproduce
```hcl

# you can assume local.kube_cluster.cluster_domain is something like example.com with the domain managed by AWS Route53

data "aws_route53_zone" "cluster" {
  name         = local.kube_cluster.cluster_domain
  private_zone = false
}

module "acm" {
  source  = "terraform-aws-modules/acm/aws"
  version = "~> 3.0"

  domain_name = local.kube_cluster.cluster_domain
  zone_id     = coalescelist(data.aws_route53_zone.cluster.*.zone_id)[0]

  subject_alternative_names = [
    "*.${local.kube_cluster.cluster_domain}",
    "${local.kube_cluster.cluster_domain}"
  ]

  wait_for_validation = true

  tags = {
    Name = local.kube_cluster.cluster_domain
  }
}
```

## Expected behavior
I am not sure. But I expect the certificate created and then the state is saved in the terraform. So the next apply attempt will not produce any changes at all.

## Actual behavior
It wants to recreate existing tf resource, such as
- module.acm.aws_acm_certificate.this[0] must be replaced
- module.acm.aws_acm_certificate_validation.this[0] must be replaced
- module.acm.aws_route53_record.validation[0] must be replaced

### Terminal Output Screenshot(s)
![image](https://user-images.githubusercontent.com/352737/123640357-48c5c700-d84b-11eb-86f0-57d2f76d3c41.png)

**Comment by antonbabenko** [comment]
It looks that a change in `subject_alternative_names` is triggering the update (`forces replacement`). Probably, this is not related to the module itself.

Can you try using version 3.0.0 of this module?

**Comment by bangau1** [comment]
@antonbabenko i just tried removing the `"${local.kube_cluster.cluster_domain}"` from the `subject_alternative_names`, since I realized that domain already handled via `domain_name` argument. And it works now. Will close this issue for now.

Thanks for replying :D
